dist: xenial
language: python
jobs:
  include:
    - python: '3.6'
    - python: '3.7'
    - python: '3.8'
    - python: pypy3.5-5.10.1
    - python: nightly
install:
  - pip install -r requirements.txt -r requirements_test.txt
script: pytest
matrix:
  fast_finish: true
