language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt -r requirements_test.txt
script:
  - pytest
  - flake8 icenews test
  - black --check .
matrix:
  fast_finish: true
